name: The Rise Report
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73628
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f26522'
    - '#ffffff'
    - '#fabc9a'
    - '#ff0000'
    - '#800000'
  brandStrength: 0.5
  lightness: 0.21942618652246892
  saturation: 0.4955610455945134
  rhythmicContrast: 0.4234426768962294
purpose: []
